---
- name: Example
  hosts: 127.0.0.1
  connection: local
  vars:
    spam_login: "{{ lookup('keepass', 'spam', 'username')}}"
    spam_password: "{{ lookup('keepass', 'spam', 'password')}}"
    ham_login: "{{ lookup('keepass', 'example/ham', 'username')}}"
    ham_password: "{{ lookup('keepass', 'example/ham', 'password')}}"
    pork_custom_property: "{{ lookup('keepass', 'example/pork', 'pork_custom_property', true)}}"
    pork_all_custom_properties: "{{ lookup('keepass', 'example/pork', '*', true)}}"

  tasks:
    - debug:
        msg: "fetch group: /    username: {{ spam_login }}    password: {{ spam_password }}"

    - debug:
        msg: "fetch group: /example/ham     username: {{ ham_login }}   password: {{ ham_password }}"

    - debug:
        msg: "fetch group: /example/pork     pork_custom: {{ pork_custom_property }}"

    - debug:
        msg: "fetch group: /example/pork     pork_all_custom_properties: {{ pork_all_custom_properties }}"